/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FifthCut: typeof import('./src/components/home/FifthCut.vue')['default']
    FirstCut: typeof import('./src/components/home/FirstCut.vue')['default']
    'Floor.Content': typeof import('./src/components/floor/Floor.Content.vue')['default']
    FloorContent: typeof import('./src/components/floor/FloorContent.vue')['default']
    FloorNav: typeof import('./src/components/floor/FloorNav.vue')['default']
    FloorTest: typeof import('./src/components/floor/FloorTest.vue')['default']
    FourthCUt: typeof import('./src/components/home/FourthCUt.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuContent: typeof import('./src/components/layout/menu/MenuContent.vue')['default']
    MenuSvg: typeof import('./src/components/layout/menu/MenuSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scaledrag: typeof import('./src/components/scaledrag.vue')['default']
    ScaleDrag: typeof import('./src/components/floor/ScaleDrag.vue')['default']
    SecondCut: typeof import('./src/components/home/SecondCut.vue')['default']
    SixthCut: typeof import('./src/components/home/SixthCut.vue')['default']
    ThirdCut: typeof import('./src/components/home/ThirdCut.vue')['default']
  }
}
