/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalculatorForm: typeof import('./src/components/calculator/CalculatorForm.vue')['default']
    CalculatorResult: typeof import('./src/components/calculator/CalculatorResult.vue')['default']
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FadeInItem: typeof import('./src/components/transition/FadeInItem.vue')['default']
    FifthCut: typeof import('./src/components/home/FifthCut.vue')['default']
    FirstCut: typeof import('./src/components/home/FirstCut.vue')['default']
    FloorContent: typeof import('./src/components/floor/FloorContent.vue')['default']
    FloorFancyBox: typeof import('./src/components/fancybox/FloorFancyBox.vue')['default']
    FloorNav: typeof import('./src/components/floor/FloorNav.vue')['default']
    FloorPoints: typeof import('./src/components/floor/FloorPoints.vue')['default']
    FloorSVG: typeof import('./src/components/floor/FloorSVG.vue')['default']
    FourthCUt: typeof import('./src/components/home/FourthCUt.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuContent: typeof import('./src/components/layout/menu/MenuContent.vue')['default']
    MenuLink: typeof import('./src/components/layout/menu/MenuLink.vue')['default']
    MenuSvg: typeof import('./src/components/layout/menu/MenuSvg.vue')['default']
    MoveBack: typeof import('./src/components/layout/moveback/MoveBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleDrag: typeof import('./src/components/floor/ScaleDrag.vue')['default']
    SecondCut: typeof import('./src/components/home/secondCut/SecondCut.vue')['default']
    SecondCutTop: typeof import('./src/components/home/secondCut/SecondCutTop.vue')['default']
    SixthCut: typeof import('./src/components/home/SixthCut.vue')['default']
    ThirdCut: typeof import('./src/components/home/ThirdCut.vue')['default']
  }
}
