/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FifthCut: typeof import('./src/components/home/FifthCut.vue')['default']
    FirstCut: typeof import('./src/components/home/FirstCut.vue')['default']
    FourthCUt: typeof import('./src/components/home/FourthCUt.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuContent: typeof import('./src/components/layout/menu/MenuContent.vue')['default']
    MenuLink: typeof import('./src/components/layout/menu/MenuLink.vue')['default']
    MenuSvg: typeof import('./src/components/layout/menu/MenuSvg.vue')['default']
    MoveBack: typeof import('./src/components/layout/moveback/MoveBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondCut: typeof import('./src/components/home/secondCut/SecondCut.vue')['default']
    SecondCutTop: typeof import('./src/components/home/secondCut/SecondCutTop.vue')['default']
    SecondThumbs: typeof import('./src/components/home/secondCut/SecondThumbs.vue')['default']
    SixthCut: typeof import('./src/components/home/SixthCut.vue')['default']
    ThirdCut: typeof import('./src/components/home/ThirdCut.vue')['default']
  }
}
